#include "K2Node_WidgetTransition.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/Widget.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"

namespace WidgetTransitionNode
{
	const FName ValueTypePinName(TEXT("ValueType"));
	const FName FromValueTypePinName(TEXT("FromValueType"));
	const FName ToValuePinName(TEXT("ToValue"));
	const FName FromValuePinName(TEXT("FromValue"));
	const FName UseFromPinName(TEXT("bUseFrom"));
	const FName WidgetPinName(TEXT("Widget"));
	const FName WidgetPropertyPinName(TEXT("WidgetProperty"));
	const FName DelayPinName(TEXT("Delay"));
	const FName TimePinName(TEXT("Time"));
	const FName RepeatCountPinName(TEXT("RepeatCount"));
	const FName YoYoPinName(TEXT("bYoYo"));
	const FName TransitionPinName(TEXT("Transition"));

	static UFunction* GetFunction(EWidgetTransitionValueType Type, bool bFrom)
	{
		const FName FunctionName = bFrom
			? (Type == EWidgetTransitionValueType::Float ? TEXT("FromFloat") : Type == EWidgetTransitionValueType::Vector2D ? TEXT("FromVector") : TEXT("FromColor"))
			: (Type == EWidgetTransitionValueType::Float ? TEXT("CreateFloatWidgetTransition") : Type == EWidgetTransitionValueType::Vector2D ? TEXT("CreateVectorWidgetTransition") : TEXT("CreateColorWidgetTransition"));
		return UWidgetTransitionFunctionLibrary::StaticClass()->FindFunctionByName(FunctionName);
	}

	static void CreateTypedPin(UK2Node* Node, EEdGraphPinDirection Direction, FName PinName, const UFunction* Function, const UEdGraphSchema_K2* Schema)
	{
		const FProperty* Property = FindFProperty<FProperty>(Function, PinName);
		FEdGraphPinType Type;
		if (!Property || !Schema->ConvertPropertyToPinType(Property, Type)) return;
		UEdGraphPin* Pin = Node->CreatePin(Direction, Type, PinName);
		FString Default;
		if (Schema->FindFunctionParameterDefaultValue(Function, Property, Default)) Schema->SetPinAutogeneratedDefaultValue(Pin, Default);
		else Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
	}

	static void ApplyAdvancedDisplay(UK2Node* Node, const UFunction* Function, UEdGraphPin* Pin)
	{
		if (!Function || !Pin) return;
		TArray<FString> AdvancedPins;
		Function->GetMetaData(TEXT("AdvancedDisplay")).ParseIntoArray(AdvancedPins, TEXT(","), true);
		Pin->bAdvancedView = AdvancedPins.ContainsByPredicate([Pin](const FString& Name) { return Pin->PinName == *Name; });
		if (Pin->bAdvancedView && Node->AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
		{
			Node->AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
		}
	}

	static void CreateTypePin(UK2Node* Node, EWidgetTransitionValueType Type, FName PinName, const UEdGraphSchema_K2* Schema)
	{
		UEdGraphPin* Pin = Node->CreatePin(EGPD_Input, Schema->PC_Byte, StaticEnum<EWidgetTransitionValueType>(), PinName);
		Pin->bNotConnectable = true;
		Pin->DefaultValue = StaticEnum<EWidgetTransitionValueType>()->GetNameStringByValue(static_cast<int64>(Type));
	}

	static void CreateBoolPin(UK2Node* Node, FName PinName, bool bDefault, const UEdGraphSchema_K2* Schema)
	{
		UEdGraphPin* Pin = Node->CreatePin(EGPD_Input, Schema->PC_Boolean, PinName);
		Pin->bNotConnectable = true;
		Pin->DefaultValue = bDefault ? TEXT("true") : TEXT("false");
	}

	static void MoveLinks(FKismetCompilerContext& CompilerContext, UK2Node* Source, UK2Node_CallFunction* Destination, FName SourcePinName, FName DestinationPinName = NAME_None)
	{
		if (DestinationPinName.IsNone()) DestinationPinName = SourcePinName;
		if (UEdGraphPin* SourcePin = Source->FindPin(SourcePinName)) if (UEdGraphPin* DestinationPin = Destination->FindPin(DestinationPinName)) CompilerContext.MovePinLinksToIntermediate(*SourcePin, *DestinationPin);
	}

	static bool ReadType(const UEdGraphPin* Pin, EWidgetTransitionValueType& OutType)
	{
		const UEnum* Enum = StaticEnum<EWidgetTransitionValueType>();
		const int64 Value = Pin && Enum ? Enum->GetValueByNameString(Pin->DefaultValue) : INDEX_NONE;
		if (Value == INDEX_NONE) return false;
		OutType = static_cast<EWidgetTransitionValueType>(Value);
		return true;
	}

	static bool ReadBool(const UEdGraphPin* Pin)
	{
		return Pin && Pin->DefaultValue.Equals(TEXT("true"), ESearchCase::IgnoreCase);
	}

	/** A value type switch is destructive by design: do not retain incompatible literals or connections as orphaned pins. */
	static void ResetTypedValuePin(UK2Node* Node, FName PinName)
	{
		UEdGraphPin* Pin = Node ? Node->FindPin(PinName) : nullptr;
		if (!Pin) return;
		TFunction<void(UEdGraphPin*)> ResetPin = [&ResetPin](UEdGraphPin* CurrentPin)
		{
			for (UEdGraphPin* SubPin : CurrentPin->SubPins) ResetPin(SubPin);
			CurrentPin->Modify();
			CurrentPin->BreakAllPinLinks();
			CurrentPin->DefaultValue.Reset();
			CurrentPin->AutogeneratedDefaultValue.Reset();
			CurrentPin->DefaultObject = nullptr;
			CurrentPin->DefaultTextValue = FText::GetEmpty();
		};
		ResetPin(Pin);
	}
}

void UK2Node_WidgetTransition::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	const UFunction* CreateFunction = WidgetTransitionNode::GetFunction(ValueType, false);
	CreatePin(EGPD_Input, Schema->PC_Object, UWidget::StaticClass(), WidgetTransitionNode::WidgetPinName);
	CreatePin(EGPD_Input, Schema->PC_Name, WidgetTransitionNode::WidgetPropertyPinName)->DefaultValue = TEXT("None");
	WidgetTransitionNode::CreateBoolPin(this, WidgetTransitionNode::UseFromPinName, bUseFrom, Schema);
	if (bUseFrom)
	{
		WidgetTransitionNode::CreateTypePin(this, FromValueType, WidgetTransitionNode::FromValueTypePinName, Schema);
		WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::FromValuePinName, WidgetTransitionNode::GetFunction(FromValueType, true), Schema);
	}
	WidgetTransitionNode::CreateTypePin(this, ValueType, WidgetTransitionNode::ValueTypePinName, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::ToValuePinName, CreateFunction, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::DelayPinName, CreateFunction, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::TimePinName, CreateFunction, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::RepeatCountPinName, CreateFunction, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::YoYoPinName, CreateFunction, Schema);
	UEdGraphPin* RepeatCountPin = FindPinChecked(WidgetTransitionNode::RepeatCountPinName);
	RepeatCountPin->PinToolTip = TEXT("Number of additional plays. Use -1 to repeat indefinitely.");
	WidgetTransitionNode::ApplyAdvancedDisplay(this, CreateFunction, FindPin(WidgetTransitionNode::DelayPinName));
	WidgetTransitionNode::ApplyAdvancedDisplay(this, CreateFunction, RepeatCountPin);
	WidgetTransitionNode::ApplyAdvancedDisplay(this, CreateFunction, FindPin(WidgetTransitionNode::YoYoPinName));
	CreatePin(EGPD_Output, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
}

void UK2Node_WidgetTransition::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	if (!bUseFrom)
	{
		// These pins are intentionally removed with Use From. Keeping them here turns them into red orphan pins.
		OldPins.RemoveAll([](const UEdGraphPin* Pin)
		{
			return Pin && (Pin->PinName == WidgetTransitionNode::FromValueTypePinName || Pin->PinName == WidgetTransitionNode::FromValuePinName);
		});
	}
	Super::ReallocatePinsDuringReconstruction(OldPins);
}

FText UK2Node_WidgetTransition::GetNodeTitle(ENodeTitleType::Type) const { return NSLOCTEXT("ElasticUMG", "CreateWidgetTransition", "Create Widget Transition"); }
FText UK2Node_WidgetTransition::GetTooltipText() const { return NSLOCTEXT("ElasticUMG", "CreateWidgetTransitionTooltip", "Creates a transition. Enable Use From to provide an explicit start value."); }
FText UK2Node_WidgetTransition::GetMenuCategory() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionCategory", "User Interface|Widget Transition"); }
void UK2Node_WidgetTransition::GetMenuActions(FBlueprintActionDatabaseRegistrar& Registrar) const { UClass* Key = GetClass(); if (Registrar.IsOpenForRegistration(Key)) Registrar.AddBlueprintAction(Key, UBlueprintNodeSpawner::Create(Key)); }

void UK2Node_WidgetTransition::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	UFunction* Function = WidgetTransitionNode::GetFunction(ValueType, false);
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->SetFromFunction(Function); Call->AllocateDefaultPins();
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::ToValuePinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::DelayPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::TimePinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::RepeatCountPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::YoYoPinName);

	UK2Node_CallFunction* BindCall = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	BindCall->SetFromFunction(UWidgetTransitionFunctionLibrary::StaticClass()->FindFunctionByName(TEXT("Bind")));
	BindCall->AllocateDefaultPins();
	if (UEdGraphPin* Return = Call->GetReturnValuePin()) if (UEdGraphPin* Transition = BindCall->FindPin(WidgetTransitionNode::TransitionPinName)) CompilerContext.GetSchema()->TryCreateConnection(Return, Transition);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, BindCall, WidgetTransitionNode::WidgetPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, BindCall, WidgetTransitionNode::WidgetPropertyPinName);

	UK2Node_CallFunction* LastCall = BindCall;
	if (bUseFrom)
	{
		UK2Node_CallFunction* FromCall = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		FromCall->SetFromFunction(WidgetTransitionNode::GetFunction(FromValueType, true));
		FromCall->AllocateDefaultPins();
		if (UEdGraphPin* Return = BindCall->GetReturnValuePin()) if (UEdGraphPin* Transition = FromCall->FindPin(WidgetTransitionNode::TransitionPinName)) CompilerContext.GetSchema()->TryCreateConnection(Return, Transition);
		WidgetTransitionNode::MoveLinks(CompilerContext, this, FromCall, WidgetTransitionNode::FromValuePinName);
		LastCall = FromCall;
	}

	if (UEdGraphPin* Output = FindPin(WidgetTransitionNode::TransitionPinName)) if (UEdGraphPin* Return = LastCall->GetReturnValuePin()) CompilerContext.MovePinLinksToIntermediate(*Output, *Return);
	BreakAllNodeLinks();
}

void UK2Node_WidgetTransition::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	EWidgetTransitionValueType NewType;
	if (Pin && Pin->PinName == WidgetTransitionNode::UseFromPinName)
	{
		const bool bNewUseFrom = WidgetTransitionNode::ReadBool(Pin);
		if (bNewUseFrom != bUseFrom)
		{
			Modify();
			if (!bNewUseFrom) WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::FromValuePinName);
			bUseFrom = bNewUseFrom;
			ReconstructNode();
		}
	}
	else if (Pin && Pin->PinName == WidgetTransitionNode::FromValueTypePinName && WidgetTransitionNode::ReadType(Pin, NewType) && NewType != FromValueType)
	{
		Modify();
		WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::FromValuePinName);
		FromValueType = NewType;
		ReconstructNode();
	}
	else if (Pin && Pin->PinName == WidgetTransitionNode::ValueTypePinName && WidgetTransitionNode::ReadType(Pin, NewType) && NewType != ValueType)
	{
		Modify();
		WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::ToValuePinName);
		ValueType = NewType;
		ReconstructNode();
	}
}

void UK2Node_WidgetTransitionFrom::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	CreatePin(EGPD_Input, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
	WidgetTransitionNode::CreateTypePin(this, ValueType, WidgetTransitionNode::ValueTypePinName, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::FromValuePinName, WidgetTransitionNode::GetFunction(ValueType, true), Schema);
	CreatePin(EGPD_Output, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
}

FText UK2Node_WidgetTransitionFrom::GetNodeTitle(ENodeTitleType::Type) const { return NSLOCTEXT("ElasticUMG", "FromWidgetTransition", "From"); }
FText UK2Node_WidgetTransitionFrom::GetTooltipText() const { return NSLOCTEXT("ElasticUMG", "FromWidgetTransitionTooltip", "Sets an explicit From endpoint. Its value type is independent from To Value."); }
FText UK2Node_WidgetTransitionFrom::GetMenuCategory() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionCategory", "User Interface|Widget Transition"); }
void UK2Node_WidgetTransitionFrom::GetMenuActions(FBlueprintActionDatabaseRegistrar&) const {}

void UK2Node_WidgetTransitionFrom::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	UFunction* Function = WidgetTransitionNode::GetFunction(ValueType, true);
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->SetFromFunction(Function); Call->AllocateDefaultPins();
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::TransitionPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::FromValuePinName);
	if (UEdGraphPin* Output = FindPin(WidgetTransitionNode::TransitionPinName, EGPD_Output)) if (UEdGraphPin* Return = Call->GetReturnValuePin()) CompilerContext.MovePinLinksToIntermediate(*Output, *Return);
	BreakAllNodeLinks();
}

void UK2Node_WidgetTransitionFrom::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	EWidgetTransitionValueType NewType;
	if (Pin && Pin->PinName == WidgetTransitionNode::ValueTypePinName && WidgetTransitionNode::ReadType(Pin, NewType) && NewType != ValueType)
	{
		Modify();
		WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::FromValuePinName);
		ValueType = NewType;
		ReconstructNode();
	}
}
