#include "K2Node_WidgetTransition.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"

namespace WidgetTransitionNode
{
	const FName ValueTypePinName(TEXT("ValueType"));
	const FName ToValuePinName(TEXT("ToValue"));
	const FName FromValuePinName(TEXT("FromValue"));
	const FName DelayPinName(TEXT("Delay"));
	const FName TimePinName(TEXT("Time"));
	const FName TransitionPinName(TEXT("Transition"));

	static UFunction* GetFunction(EWidgetTransitionValueType Type, bool bFrom)
	{
		const FName FunctionName = bFrom
			? (Type == EWidgetTransitionValueType::Float ? TEXT("FromFloat") : Type == EWidgetTransitionValueType::Vector2D ? TEXT("FromVector") : TEXT("FromColor"))
			: (Type == EWidgetTransitionValueType::Float ? TEXT("CreateFloatWidgetTransition") : Type == EWidgetTransitionValueType::Vector2D ? TEXT("CreateVectorWidgetTransition") : TEXT("CreateColorWidgetTransition"));
		return UWidgetTransitionFunctionLibrary::StaticClass()->FindFunctionByName(FunctionName);
	}

	static void CreateTypedPin(UK2Node* Node, EEdGraphPinDirection Direction, FName PinName, const UFunction* Function, const UEdGraphSchema_K2* Schema)
	{
		const FProperty* Property = FindFProperty<FProperty>(Function, PinName);
		FEdGraphPinType Type;
		if (!Property || !Schema->ConvertPropertyToPinType(Property, Type)) return;
		UEdGraphPin* Pin = Node->CreatePin(Direction, Type, PinName);
		FString Default;
		if (Schema->FindFunctionParameterDefaultValue(Function, Property, Default)) Schema->SetPinAutogeneratedDefaultValue(Pin, Default);
		else Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
	}

	static void CreateTypePin(UK2Node* Node, EWidgetTransitionValueType Type, const UEdGraphSchema_K2* Schema)
	{
		UEdGraphPin* Pin = Node->CreatePin(EGPD_Input, Schema->PC_Byte, StaticEnum<EWidgetTransitionValueType>(), ValueTypePinName);
		Pin->bNotConnectable = true;
		Pin->DefaultValue = StaticEnum<EWidgetTransitionValueType>()->GetNameStringByValue(static_cast<int64>(Type));
	}

	static void MoveLinks(FKismetCompilerContext& CompilerContext, UK2Node* Source, UK2Node_CallFunction* Destination, FName PinName)
	{
		if (UEdGraphPin* SourcePin = Source->FindPin(PinName)) if (UEdGraphPin* DestinationPin = Destination->FindPin(PinName)) CompilerContext.MovePinLinksToIntermediate(*SourcePin, *DestinationPin);
	}

	static bool ReadType(const UEdGraphPin* Pin, EWidgetTransitionValueType& OutType)
	{
		const UEnum* Enum = StaticEnum<EWidgetTransitionValueType>();
		const int64 Value = Pin && Enum ? Enum->GetValueByNameString(Pin->DefaultValue) : INDEX_NONE;
		if (Value == INDEX_NONE) return false;
		OutType = static_cast<EWidgetTransitionValueType>(Value);
		return true;
	}

	/** A value type switch is destructive by design: do not retain incompatible literals or connections as orphaned pins. */
	static void ResetTypedValuePin(UK2Node* Node, FName PinName)
	{
		UEdGraphPin* Pin = Node ? Node->FindPin(PinName) : nullptr;
		if (!Pin) return;
		TFunction<void(UEdGraphPin*)> ResetPin = [&ResetPin](UEdGraphPin* CurrentPin)
		{
			for (UEdGraphPin* SubPin : CurrentPin->SubPins) ResetPin(SubPin);
			CurrentPin->Modify();
			CurrentPin->BreakAllPinLinks();
			CurrentPin->DefaultValue.Reset();
			CurrentPin->AutogeneratedDefaultValue.Reset();
			CurrentPin->DefaultObject = nullptr;
			CurrentPin->DefaultTextValue = FText::GetEmpty();
		};
		ResetPin(Pin);
	}
}

void UK2Node_WidgetTransition::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	WidgetTransitionNode::CreateTypePin(this, ValueType, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::ToValuePinName, WidgetTransitionNode::GetFunction(ValueType, false), Schema);
	CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::DelayPinName)->DefaultValue = TEXT("0.0");
	CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::TimePinName)->DefaultValue = TEXT("0.2");
	CreatePin(EGPD_Output, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
}

FText UK2Node_WidgetTransition::GetNodeTitle(ENodeTitleType::Type) const { return NSLOCTEXT("ElasticUMG", "CreateWidgetTransition", "Create Widget Transition"); }
FText UK2Node_WidgetTransition::GetTooltipText() const { return NSLOCTEXT("ElasticUMG", "CreateWidgetTransitionTooltip", "Creates a transition. Value Type determines the type of To Value."); }
FText UK2Node_WidgetTransition::GetMenuCategory() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionCategory", "User Interface|Widget Transition"); }
void UK2Node_WidgetTransition::GetMenuActions(FBlueprintActionDatabaseRegistrar& Registrar) const { UClass* Key = GetClass(); if (Registrar.IsOpenForRegistration(Key)) Registrar.AddBlueprintAction(Key, UBlueprintNodeSpawner::Create(Key)); }

void UK2Node_WidgetTransition::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	UFunction* Function = WidgetTransitionNode::GetFunction(ValueType, false);
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->SetFromFunction(Function); Call->AllocateDefaultPins();
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::ToValuePinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::DelayPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::TimePinName);
	if (UEdGraphPin* Output = FindPin(WidgetTransitionNode::TransitionPinName)) if (UEdGraphPin* Return = Call->GetReturnValuePin()) CompilerContext.MovePinLinksToIntermediate(*Output, *Return);
	BreakAllNodeLinks();
}

void UK2Node_WidgetTransition::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	EWidgetTransitionValueType NewType;
	if (Pin && Pin->PinName == WidgetTransitionNode::ValueTypePinName && WidgetTransitionNode::ReadType(Pin, NewType) && NewType != ValueType)
	{
		Modify();
		WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::ToValuePinName);
		ValueType = NewType;
		ReconstructNode();
	}
}

void UK2Node_WidgetTransitionFrom::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	CreatePin(EGPD_Input, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
	WidgetTransitionNode::CreateTypePin(this, ValueType, Schema);
	WidgetTransitionNode::CreateTypedPin(this, EGPD_Input, WidgetTransitionNode::FromValuePinName, WidgetTransitionNode::GetFunction(ValueType, true), Schema);
	CreatePin(EGPD_Output, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
}

FText UK2Node_WidgetTransitionFrom::GetNodeTitle(ENodeTitleType::Type) const { return NSLOCTEXT("ElasticUMG", "FromWidgetTransition", "From"); }
FText UK2Node_WidgetTransitionFrom::GetTooltipText() const { return NSLOCTEXT("ElasticUMG", "FromWidgetTransitionTooltip", "Sets an explicit From endpoint. Its value type is independent from To Value."); }
FText UK2Node_WidgetTransitionFrom::GetMenuCategory() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionCategory", "User Interface|Widget Transition"); }
void UK2Node_WidgetTransitionFrom::GetMenuActions(FBlueprintActionDatabaseRegistrar& Registrar) const { UClass* Key = GetClass(); if (Registrar.IsOpenForRegistration(Key)) Registrar.AddBlueprintAction(Key, UBlueprintNodeSpawner::Create(Key)); }

void UK2Node_WidgetTransitionFrom::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	UFunction* Function = WidgetTransitionNode::GetFunction(ValueType, true);
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->SetFromFunction(Function); Call->AllocateDefaultPins();
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::TransitionPinName);
	WidgetTransitionNode::MoveLinks(CompilerContext, this, Call, WidgetTransitionNode::FromValuePinName);
	if (UEdGraphPin* Output = FindPin(WidgetTransitionNode::TransitionPinName, EGPD_Output)) if (UEdGraphPin* Return = Call->GetReturnValuePin()) CompilerContext.MovePinLinksToIntermediate(*Output, *Return);
	BreakAllNodeLinks();
}

void UK2Node_WidgetTransitionFrom::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	EWidgetTransitionValueType NewType;
	if (Pin && Pin->PinName == WidgetTransitionNode::ValueTypePinName && WidgetTransitionNode::ReadType(Pin, NewType) && NewType != ValueType)
	{
		Modify();
		WidgetTransitionNode::ResetTypedValuePin(this, WidgetTransitionNode::FromValuePinName);
		ValueType = NewType;
		ReconstructNode();
	}
}
