#include "K2Node_WidgetTransition.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Widget.h"
#include "EdGraphSchema_K2.h"
#include "EdGraphUtilities.h"
#include "K2Node_CallFunction.h"
#include "K2Node_VariableGet.h"
#include "KismetCompiler.h"
#include "WidgetBlueprint.h"

namespace WidgetTransitionNode
{
	static const FName WidgetPinName(TEXT("Widget"));
	static const FName WidgetPropertyPinName(TEXT("WidgetProperty"));
	static const FName ValueTypePinName(TEXT("ValueType"));
	static const FName FromValuePinName(TEXT("FromValue"));
	static const FName ToValuePinName(TEXT("ToValue"));
	static const FName TimePinName(TEXT("Time"));
	static const FName DelayPinName(TEXT("Delay"));
	static const FName ApplyValueBeforeDelayPinName(TEXT("bApplyValueBeforeDelay"));
	static const FName EasingPinName(TEXT("Easing"));
	static const FName EasingControlPoint1PinName(TEXT("EasingControlPoint1"));
	static const FName EasingControlPoint2PinName(TEXT("EasingControlPoint2"));
	static const FName RepeatCountPinName(TEXT("RepeatCount"));
	static const FName YoYoPinName(TEXT("bYoYo"));
	static const FName RemoveFromParentPinName(TEXT("bRemoveFromParent"));
	static const FName UseSpringPinName(TEXT("bUseSpring"));
	static const FName SpringSpeedPinName(TEXT("SpringSpeed"));
	static const FName SpringBouncePinName(TEXT("SpringBounce"));
	static const FName LegacySpringFactorPinName(TEXT("SpringFactor"));
	static const FName LegacyDampingFactorPinName(TEXT("DampingFactor"));
	static const FName LegacyMaxVelocityPinName(TEXT("MaxVelocity"));
	static const FName LegacyCompleteTolerancePinName(TEXT("CompleteTolerance"));
	static const FName OnUpdatePinName(TEXT("OnUpdate"));
	static const FName OnStartedPinName(TEXT("OnStarted"));
	static const FName OnFinishedPinName(TEXT("OnFinished"));
	static const FName WorldContextPinName(TEXT("WorldContextObject"));
	static const FName UseFromPinName(TEXT("bUseFrom"));
	static const FName TransitionPinName(TEXT("Transition"));

	/** Finds the typed runtime entry point from UFUNCTION metadata rather than a hard-coded name table. */
	static UFunction* GetTransitionFunction(EWidgetTransitionValueType ValueType)
	{
		const FString ExpectedValueType = StaticEnum<EWidgetTransitionValueType>()->GetNameStringByValue(static_cast<int64>(ValueType));
		for (TFieldIterator<UFunction> It(UWidgetTransitionFunctionLibrary::StaticClass()); It; ++It)
		{
			UFunction* Function = *It;
			if (Function->HasMetaData(TEXT("ElasticUMGTransition")) && Function->GetMetaData(TEXT("ElasticUMGValueType")) == ExpectedValueType) return Function;
		}
		return nullptr;
	}

	static const FProperty* FindTransitionParameter(const UFunction* Function, FName Role)
	{
		if (!Function) return nullptr;
		for (TFieldIterator<FProperty> It(Function); It; ++It)
		{
			const FProperty* Property = *It;
			if (Property->GetMetaData(TEXT("ElasticUMGRole")) == Role.ToString()) return Property;
		}
		return FindFProperty<FProperty>(Function, Role);
	}

	static void CreateValuePin(UK2Node_WidgetTransition* Node, EEdGraphPinDirection Direction, FName Name, const UEdGraphSchema_K2* Schema)
	{
		if (!Node->IsValueTypeResolved()) { Node->CreatePin(Direction, Schema->PC_Wildcard, Name); return; }
		UFunction* Function = GetTransitionFunction(Node->GetValueType());
		const FProperty* Parameter = FindTransitionParameter(Function, Name);
		FEdGraphPinType PinType;
		if (!Parameter || !Schema->ConvertPropertyToPinType(Parameter, PinType)) return;
		UEdGraphPin* Pin = Node->CreatePin(Direction, PinType, Name);
		FString DefaultValue;
		if (Function && Schema->FindFunctionParameterDefaultValue(Function, Parameter, DefaultValue)) Schema->SetPinAutogeneratedDefaultValue(Pin, DefaultValue);
		else Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
	}

	static void NormalizeVector2DDefault(UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinType.PinSubCategoryObject != TBaseStructure<FVector2D>::Get() || Pin->DefaultValue.StartsWith(TEXT("("))) return;
		int32 YOffset = INDEX_NONE;
		if (!Pin->DefaultValue.FindChar(TEXT('Y'), YOffset) || !Pin->DefaultValue.Mid(YOffset).StartsWith(TEXT("Y="))) return;
		const FString XValue = Pin->DefaultValue.Left(YOffset).TrimEnd();
		const FString YValue = Pin->DefaultValue.Mid(YOffset);
		if (XValue.StartsWith(TEXT("X="))) Pin->DefaultValue = FString::Printf(TEXT("(%s,%s)"), *XValue, *YValue);
	}

	static void CreateFunctionParameterPin(UK2Node_WidgetTransition* Node, FName ParameterName, const UEdGraphSchema_K2* Schema)
	{
		if (!Node->IsValueTypeResolved()) return;
		UFunction* Function = GetTransitionFunction(Node->GetValueType());
		const FProperty* Parameter = FindTransitionParameter(Function, ParameterName);
		FEdGraphPinType PinType;
		if (Parameter && Schema->ConvertPropertyToPinType(Parameter, PinType))
		{
			UEdGraphPin* Pin = Node->CreatePin(EGPD_Input, PinType, ParameterName);
			FString DefaultValue;
			if (Schema->FindFunctionParameterDefaultValue(Function, Parameter, DefaultValue)) Schema->SetPinAutogeneratedDefaultValue(Pin, DefaultValue);
			else Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
		}
	}

	static void SetEasingDefault(UEdGraphPin* Pin, const FWidgetTransitionEasingValue& Value)
	{
		if (!Pin) return;
		const FString DefaultValue = FString::Printf(TEXT("(ControlPoint1=(X=%g,Y=%g),ControlPoint2=(X=%g,Y=%g))"), Value.ControlPoint1.X, Value.ControlPoint1.Y, Value.ControlPoint2.X, Value.ControlPoint2.Y);
		Pin->DefaultValue = DefaultValue;
		Pin->AutogeneratedDefaultValue = DefaultValue;
	}

	static bool IsInfiniteRepeat(const UEdGraphPin* Pin)
	{
		return Pin && Pin->LinkedTo.IsEmpty() && Pin->DefaultValue == TEXT("-1");
	}

	static TOptional<EWidgetTransitionValueType> GetSelectedPropertyValueType(const UK2Node_WidgetTransition* Node)
	{
		const UEdGraphPin* PropertyPathPin = Node ? Node->FindPin(WidgetPropertyPinName) : nullptr;
		const FString PropertyPath = PropertyPathPin ? PropertyPathPin->GetDefaultAsString() : FString();
		const UEdGraphPin* WidgetPin = Node ? Node->FindPin(WidgetPinName) : nullptr;
		if (PropertyPath.IsEmpty() || !WidgetPin || WidgetPin->LinkedTo.IsEmpty()) return {};

		UEdGraphPin* SourcePin = FEdGraphUtilities::GetNetFromPin(WidgetPin->LinkedTo[0]);
		UStruct* CurrentStruct = SourcePin ? Cast<UClass>(SourcePin->PinType.PinSubCategoryObject.Get()) : nullptr;
		const UK2Node_VariableGet* VariableGet = SourcePin ? Cast<UK2Node_VariableGet>(SourcePin->GetOwningNode()) : nullptr;
		UWidgetBlueprint* WidgetBlueprint = SourcePin && SourcePin->GetOwningNode() ? SourcePin->GetOwningNode()->GetTypedOuter<UWidgetBlueprint>() : nullptr;
		UWidget* DesignerWidget = VariableGet && WidgetBlueprint && WidgetBlueprint->WidgetTree ? WidgetBlueprint->WidgetTree->FindWidget(VariableGet->GetVarName()) : nullptr;
		FString RelativePath = PropertyPath;
		if (PropertyPath.StartsWith(TEXT("Slot.")))
		{
			CurrentStruct = DesignerWidget && DesignerWidget->Slot ? DesignerWidget->Slot->GetClass() : nullptr;
			RelativePath.RightChopInline(5);
		}

		TArray<FString> Segments;
		RelativePath.ParseIntoArray(Segments, TEXT("."), true);
		for (int32 Index = 0; CurrentStruct && Index < Segments.Num(); ++Index)
		{
			const FProperty* Property = FindFProperty<FProperty>(CurrentStruct, *Segments[Index]);
			if (!Property) return {};
			if (Index + 1 < Segments.Num())
			{
				const FStructProperty* StructProperty = CastField<FStructProperty>(Property);
				CurrentStruct = StructProperty ? StructProperty->Struct : nullptr;
				continue;
			}
			if (Property->IsA<FFloatProperty>() || Property->IsA<FDoubleProperty>()) return EWidgetTransitionValueType::Float;
			if (Property->IsA<FBoolProperty>()) return EWidgetTransitionValueType::Bool;
			if (const FStructProperty* StructProperty = CastField<FStructProperty>(Property))
			{
				if (StructProperty->Struct == TBaseStructure<FVector2D>::Get()) return EWidgetTransitionValueType::Vector2D;
				if (StructProperty->Struct == TBaseStructure<FLinearColor>::Get()) return EWidgetTransitionValueType::LinearColor;
			}
		}
		return {};
	}

	static bool IsDiscardableTypeSpecificPin(const UEdGraphPin* Pin)
	{
		if (!Pin || !Pin->bOrphanedPin || !Pin->LinkedTo.IsEmpty()) return false;
		const FName Name = Pin->PinName;
	return Name == FromValuePinName || Name == TimePinName || Name == DelayPinName || Name == ApplyValueBeforeDelayPinName || Name == RepeatCountPinName
			|| Name == EasingPinName
			|| Name == EasingControlPoint1PinName || Name == EasingControlPoint2PinName
			|| Name == YoYoPinName || Name == RemoveFromParentPinName || Name == UseSpringPinName
			|| Name == SpringSpeedPinName || Name == SpringBouncePinName || Name == LegacySpringFactorPinName || Name == LegacyDampingFactorPinName || Name == LegacyMaxVelocityPinName
			|| Name == LegacyCompleteTolerancePinName || Name == OnUpdatePinName || Name == OnStartedPinName || Name == OnFinishedPinName || Name == ValueTypePinName;
	}
}

void UK2Node_WidgetTransition::ShowExecutionPins(const UEdGraphSchema_K2* Schema)
{
	CreatePin(EGPD_Input, Schema->PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, Schema->PC_Exec, UEdGraphSchema_K2::PN_Then);
	UEdGraphPin* WorldContextPin = CreatePin(EGPD_Input, Schema->PC_Object, UObject::StaticClass(), WidgetTransitionNode::WorldContextPinName);
	WorldContextPin->DefaultValue = TEXT("self"); WorldContextPin->bHidden = true;
}

void UK2Node_WidgetTransition::ShowWidgetSelectionPins(const UEdGraphSchema_K2* Schema)
{
	const bool bShowWidgetAndProperty = IsOptionalPinVisible(EWidgetTransitionOptionalPin::WidgetAndProperty);
	UEdGraphPin* WidgetPin = CreatePin(EGPD_Input, Schema->PC_Object, UWidget::StaticClass(), WidgetTransitionNode::WidgetPinName);
	WidgetPin->bHidden = !bShowWidgetAndProperty;
	UEdGraphPin* WidgetPropertyPin = CreatePin(EGPD_Input, Schema->PC_String, WidgetTransitionNode::WidgetPropertyPinName);
	WidgetPropertyPin->bHidden = !bShowWidgetAndProperty;
}

void UK2Node_WidgetTransition::ShowValueTypePinWhenWidgetSelectionIsHidden(const UEdGraphSchema_K2* Schema)
{
	if (IsOptionalPinVisible(EWidgetTransitionOptionalPin::WidgetAndProperty)) return;
	UEdGraphPin* ValueTypePin = CreatePin(EGPD_Input, Schema->PC_Byte, StaticEnum<EWidgetTransitionValueType>(), WidgetTransitionNode::ValueTypePinName);
	ValueTypePin->bNotConnectable = true;
	ValueTypePin->DefaultValue = StaticEnum<EWidgetTransitionValueType>()->GetNameStringByValue(static_cast<int64>(ManualValueType));
}

void UK2Node_WidgetTransition::ShowTransitionValuePins(const UEdGraphSchema_K2* Schema)
{
	if (IsOptionalPinVisible(EWidgetTransitionOptionalPin::From))
	{
		WidgetTransitionNode::CreateValuePin(this, EGPD_Input, WidgetTransitionNode::FromValuePinName, Schema);
		if (bValuePinsDisabled)
		{
			UEdGraphPin* FromPin = FindPinChecked(WidgetTransitionNode::FromValuePinName);
			FromPin->bNotConnectable = true;
			FromPin->bDefaultValueIsReadOnly = true;
		}
	}
	WidgetTransitionNode::CreateValuePin(this, EGPD_Input, WidgetTransitionNode::ToValuePinName, Schema);
	if (bValuePinsDisabled)
	{
		UEdGraphPin* ToPin = FindPinChecked(WidgetTransitionNode::ToValuePinName);
		ToPin->bNotConnectable = true;
		ToPin->bDefaultValueIsReadOnly = true;
	}
}

void UK2Node_WidgetTransition::ShowTimingAndEasingPins(const UEdGraphSchema_K2* Schema)
{
	if (IsOptionalPinVisible(EWidgetTransitionOptionalPin::Delay))
	{
		CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::DelayPinName)->DefaultValue = TEXT("0.0");
		UEdGraphPin* ApplyBeforeDelayPin = CreatePin(EGPD_Input, Schema->PC_Boolean, WidgetTransitionNode::ApplyValueBeforeDelayPinName);
		ApplyBeforeDelayPin->DefaultValue = TEXT("true");
	}
	if (!IsOptionalPinVisible(EWidgetTransitionOptionalPin::Spring)) CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::TimePinName)->DefaultValue = TEXT("0.2");
	if (!IsOptionalPinVisible(EWidgetTransitionOptionalPin::Spring))
	{
		UEdGraphPin* EasingPin = CreatePin(EGPD_Input, Schema->PC_Struct, FWidgetTransitionEasingValue::StaticStruct(), WidgetTransitionNode::EasingPinName);
		WidgetTransitionNode::SetEasingDefault(EasingPin, GetDisplayedEasingValue());
		if (!IsCustomEasingSelected())
		{
			EasingPin->bNotConnectable = true;
			EasingPin->bDefaultValueIsReadOnly = true;
		}
	}
}

void UK2Node_WidgetTransition::ShowRepeatPin(const UEdGraphSchema_K2* Schema)
{
	CreatePin(EGPD_Input, Schema->PC_Int, WidgetTransitionNode::RepeatCountPinName)->DefaultValue = TEXT("0");
}

bool UK2Node_WidgetTransition::SupportsSpring() const
{
	return SupportsTransitionMode(TEXT("Spring"));
}

bool UK2Node_WidgetTransition::SupportsTransitionMode(FName Mode) const
{
	if (!bValueTypeResolved) return false;
	const UFunction* Function = WidgetTransitionNode::GetTransitionFunction(ValueType);
	if (!Function) return false;
	TArray<FString> Modes;
	Function->GetMetaData(TEXT("ElasticUMGModes")).ParseIntoArray(Modes, TEXT(","), true);
	return Modes.ContainsByPredicate([Mode](const FString& Candidate) { return Candidate.Equals(Mode.ToString(), ESearchCase::IgnoreCase); });
}

bool UK2Node_WidgetTransition::ShowSpringPins(const UEdGraphSchema_K2* Schema)
{
	if (IsOptionalPinVisible(EWidgetTransitionOptionalPin::Spring) && SupportsSpring())
	{
		UEdGraphPin* SpringSpeedPin = CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::SpringSpeedPinName);
		SpringSpeedPin->DefaultValue = TEXT("0.65");
		UEdGraphPin* SpringBouncePin = CreatePin(EGPD_Input, Schema->PC_Real, Schema->PC_Float, WidgetTransitionNode::SpringBouncePinName);
		SpringBouncePin->DefaultValue = TEXT("0.45");
		return false;
	}
	return false;
}

bool UK2Node_WidgetTransition::ShowUpdatePin(const UEdGraphSchema_K2* Schema)
{
	WidgetTransitionNode::CreateFunctionParameterPin(this, WidgetTransitionNode::OnUpdatePinName, Schema);
	if (UEdGraphPin* OnUpdatePin = FindPin(WidgetTransitionNode::OnUpdatePinName))
	{
		OnUpdatePin->bAdvancedView = true;
		return true;
	}
	return false;
}

bool UK2Node_WidgetTransition::ShowAdvancedPins(const UEdGraphSchema_K2* Schema)
{
	WidgetTransitionNode::CreateFunctionParameterPin(this, WidgetTransitionNode::YoYoPinName, Schema);
	WidgetTransitionNode::CreateFunctionParameterPin(this, WidgetTransitionNode::RemoveFromParentPinName, Schema);
	WidgetTransitionNode::CreateFunctionParameterPin(this, WidgetTransitionNode::OnStartedPinName, Schema);
	WidgetTransitionNode::CreateFunctionParameterPin(this, WidgetTransitionNode::OnFinishedPinName, Schema);
	bool bHasPins = false;
	for (const FName PinName : { WidgetTransitionNode::YoYoPinName, WidgetTransitionNode::RemoveFromParentPinName, WidgetTransitionNode::OnStartedPinName, WidgetTransitionNode::OnFinishedPinName })
	{
		if (UEdGraphPin* Pin = FindPin(PinName))
		{
			Pin->bAdvancedView = true;
			bHasPins = true;
		}
	}
	return bHasPins;
}

void UK2Node_WidgetTransition::UpdateAdvancedPinVisibility(bool bHasAdvancedPins)
{
	if (bHasAdvancedPins && AdvancedPinDisplay == ENodeAdvancedPins::NoPins) AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
}

void UK2Node_WidgetTransition::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	// This node only chooses the strongly typed endpoint builder. Common options
	// are composed by the pure With* nodes and execution happens in Start Widget Transition.
	ShowWidgetSelectionPins(Schema);
	ShowValueTypePinWhenWidgetSelectionIsHidden(Schema);
	ShowTransitionValuePins(Schema);
	CreatePin(EGPD_Output, Schema->PC_Struct, FWidgetTransition::StaticStruct(), WidgetTransitionNode::TransitionPinName);
}

FText UK2Node_WidgetTransition::GetNodeTitle(ENodeTitleType::Type) const { return NSLOCTEXT("ElasticUMG", "CreateWidgetTransition", "Create Widget Transition"); }
FText UK2Node_WidgetTransition::GetTooltipText() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionNodeTooltip", "Animates a selected property of the input widget. From is optional; when omitted, the current property value is used."); }
FText UK2Node_WidgetTransition::GetMenuCategory() const { return NSLOCTEXT("ElasticUMG", "WidgetTransitionNodeCategory", "User Interface"); }

void UK2Node_WidgetTransition::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey)) ActionRegistrar.AddBlueprintAction(ActionKey, UBlueprintNodeSpawner::Create(ActionKey));
}

void UK2Node_WidgetTransition::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	// UE 5.7's RecombinePin writes FVector2D as "X=… Y=…", while UHT expects struct text.
	// Normalize after Super so both split and recombined pins compile through this custom node.
	WidgetTransitionNode::NormalizeVector2DDefault(FindPin(WidgetTransitionNode::FromValuePinName));
	WidgetTransitionNode::NormalizeVector2DDefault(FindPin(WidgetTransitionNode::ToValuePinName));
	if (!bValueTypeResolved)
	{
		CompilerContext.MessageLog.Error(*NSLOCTEXT("ElasticUMG", "UnresolvedWidgetTransitionType", "@@ requires a Widget Property to resolve its wildcard value type.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	if (bValuePinsDisabled)
	{
		CompilerContext.MessageLog.Error(*NSLOCTEXT("ElasticUMG", "MissingWidgetTransitionProperty", "@@ requires a valid Widget Property while Wp is enabled.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}
	UFunction* Function = WidgetTransitionNode::GetTransitionFunction(ValueType);
	if (!Function) { CompilerContext.MessageLog.Error(*NSLOCTEXT("ElasticUMG", "MissingWidgetTransitionFunction", "@@ could not find its transition function.").ToString(), this); BreakAllNodeLinks(); return; }
	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(Function); CallNode->AllocateDefaultPins();
	const UEdGraphPin* FromPin = FindPin(WidgetTransitionNode::FromValuePinName);
	const bool bUseFrom = FromPin && (!FromPin->LinkedTo.IsEmpty() || !FromPin->DefaultValue.IsEmpty());
	const auto MoveLinks = [&CompilerContext, this, CallNode](FName PinName)
	{
		if (UEdGraphPin* SourcePin = FindPin(PinName)) if (UEdGraphPin* DestinationPin = CallNode->FindPin(PinName)) CompilerContext.MovePinLinksToIntermediate(*SourcePin, *DestinationPin);
	};
	MoveLinks(WidgetTransitionNode::WidgetPinName); MoveLinks(WidgetTransitionNode::WidgetPropertyPinName); MoveLinks(WidgetTransitionNode::FromValuePinName);
	MoveLinks(WidgetTransitionNode::ToValuePinName);
	if (UEdGraphPin* SourcePin = FindPin(WidgetTransitionNode::TransitionPinName))
	{
		if (UEdGraphPin* DestinationPin = CallNode->GetReturnValuePin()) CompilerContext.MovePinLinksToIntermediate(*SourcePin, *DestinationPin);
	}
	CallNode->FindPinChecked(WidgetTransitionNode::UseFromPinName)->DefaultValue = bUseFrom ? TEXT("true") : TEXT("false");
	if (UEdGraphPin* SpringPin = CallNode->FindPin(WidgetTransitionNode::UseSpringPinName)) SpringPin->DefaultValue = IsOptionalPinVisible(EWidgetTransitionOptionalPin::Spring) ? TEXT("true") : TEXT("false");
	BreakAllNodeLinks();
}

void UK2Node_WidgetTransition::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == WidgetTransitionNode::ValueTypePinName)
	{
		const UEnum* ValueTypeEnum = StaticEnum<EWidgetTransitionValueType>();
		const int64 EnumValue = ValueTypeEnum ? ValueTypeEnum->GetValueByNameString(Pin->DefaultValue) : INDEX_NONE;
		if (EnumValue != INDEX_NONE) SetValueType(static_cast<EWidgetTransitionValueType>(EnumValue));
		return;
	}
	if (Pin && Pin->PinName == WidgetTransitionNode::WidgetPropertyPinName && IsOptionalPinVisible(EWidgetTransitionOptionalPin::WidgetAndProperty) && Pin->DefaultValue.IsEmpty())
	{
		Modify();
		bValuePinsDisabled = true;
		ReconstructNode();
		return;
	}
	if (Pin && Pin->PinName == WidgetTransitionNode::RepeatCountPinName)
	{
		const bool bNewInfinite = WidgetTransitionNode::IsInfiniteRepeat(Pin);
		if (bRepeatCountIsInfinite != bNewInfinite) { Modify(); bRepeatCountIsInfinite = bNewInfinite; ReconstructNode(); }
	}
}

void UK2Node_WidgetTransition::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);
	if (Pin && Pin->PinName == WidgetTransitionNode::RepeatCountPinName)
	{
		const bool bNewInfinite = WidgetTransitionNode::IsInfiniteRepeat(Pin);
		if (bRepeatCountIsInfinite != bNewInfinite) { Modify(); bRepeatCountIsInfinite = bNewInfinite; ReconstructNode(); }
	}
}

void UK2Node_WidgetTransition::PostReconstructNode()
{
	Super::PostReconstructNode();
	for (UEdGraphPin* Pin : Pins) WidgetTransitionNode::NormalizeVector2DDefault(Pin);
	// One-time migration from the earlier Name + two-vector representation.
	for (const UEdGraphPin* Pin : Pins)
	{
		if (!Pin->bOrphanedPin || Pin->PinName != WidgetTransitionNode::EasingPinName || Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Name) continue;
		const FString LegacyPreset = Pin->GetDefaultAsString();
		if (!LegacyPreset.IsEmpty()) SelectedEasingPreset = FName(*LegacyPreset);
		break;
	}
	if (IsCustomEasingSelected())
	{
		FWidgetTransitionEasingValue LegacyValue = GetDisplayedEasingValue();
		for (const UEdGraphPin* Pin : Pins)
		{
			if (!Pin->bOrphanedPin) continue;
			if (Pin->PinName == WidgetTransitionNode::EasingControlPoint1PinName) LegacyValue.ControlPoint1.InitFromString(Pin->GetDefaultAsString());
			if (Pin->PinName == WidgetTransitionNode::EasingControlPoint2PinName) LegacyValue.ControlPoint2.InitFromString(Pin->GetDefaultAsString());
		}
		WidgetTransitionNode::SetEasingDefault(FindPin(WidgetTransitionNode::EasingPinName), LegacyValue);
	}
	const auto MigrateLegacyToggle = [this](EWidgetTransitionOptionalPin LegacyOption, FName PinName)
	{
		if (!IsOptionalPinVisible(LegacyOption)) return;
		if (UEdGraphPin* Pin = FindPin(PinName))
		{
			Pin->DefaultValue = TEXT("true");
			Pin->AutogeneratedDefaultValue = TEXT("true");
		}
		OptionalPins &= ~static_cast<int32>(LegacyOption);
	};
	// Convert old tab state once; subsequent edits use the regular bool pins.
	MigrateLegacyToggle(EWidgetTransitionOptionalPin::YoYo, WidgetTransitionNode::YoYoPinName);
	MigrateLegacyToggle(EWidgetTransitionOptionalPin::RemoveFromParent, WidgetTransitionNode::RemoveFromParentPinName);
	TArray<UEdGraphPin*> PinsToDiscard;
	for (UEdGraphPin* Pin : Pins)
	{
		if (WidgetTransitionNode::IsDiscardableTypeSpecificPin(Pin)) PinsToDiscard.Add(Pin);
	}
	if (PinsToDiscard.IsEmpty()) return;
	for (UEdGraphPin* Pin : PinsToDiscard) Pins.Remove(Pin);
	DestroyPinList(PinsToDiscard);
}

bool UK2Node_WidgetTransition::CanSplitPin(const UEdGraphPin* Pin) const
{
	return (!Pin || Pin->PinName != WidgetTransitionNode::EasingPinName || IsCustomEasingSelected()) && Super::CanSplitPin(Pin);
}

void UK2Node_WidgetTransition::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);
	if (PropertyChangedEvent.GetPropertyName() == GET_MEMBER_NAME_CHECKED(UK2Node_WidgetTransition, OptionalPins))
	{
		Modify();
		ReconstructNode();
	}
}

void UK2Node_WidgetTransition::SetValueType(EWidgetTransitionValueType InValueType)
{
	if (!bValueTypeResolved || ValueType != InValueType)
	{
		Modify();
		ValueType = InValueType;
		ManualValueType = InValueType;
		bValueTypeResolved = true;
		bValuePinsDisabled = false;
		if (!SupportsTransitionMode(TEXT("Spring")))
		{
			OptionalPins &= ~static_cast<int32>(EWidgetTransitionOptionalPin::Spring);
			bShowEasing = true;
		}
		ReconstructNode();
	}
}

void UK2Node_WidgetTransition::SetOptionalPins(int32 InOptionalPins)
{
	if (OptionalPins != InOptionalPins)
	{
		Modify();
		const bool bWasShowingWidgetAndProperty = IsOptionalPinVisible(EWidgetTransitionOptionalPin::WidgetAndProperty);
		OptionalPins = InOptionalPins;
		const bool bIsShowingWidgetAndProperty = IsOptionalPinVisible(EWidgetTransitionOptionalPin::WidgetAndProperty);
		if (!bWasShowingWidgetAndProperty && bIsShowingWidgetAndProperty)
		{
			if (const TOptional<EWidgetTransitionValueType> PropertyType = WidgetTransitionNode::GetSelectedPropertyValueType(this))
			{
				ValueType = PropertyType.GetValue();
				bValueTypeResolved = true;
				bValuePinsDisabled = false;
			}
			else bValuePinsDisabled = true;
		}
		else if (bWasShowingWidgetAndProperty && !bIsShowingWidgetAndProperty)
		{
			ValueType = ManualValueType;
			bValueTypeResolved = true;
			bValuePinsDisabled = false;
		}
		ReconstructNode();
	}
}

void UK2Node_WidgetTransition::SetEasingVisible(bool bInShowEasing)
{
	if (bShowEasing != bInShowEasing)
	{
		Modify();
		bShowEasing = bInShowEasing;
		ReconstructNode();
	}
}

void UK2Node_WidgetTransition::SetTransitionMode(bool bInUseSpring)
{
	if (bInUseSpring && !SupportsTransitionMode(TEXT("Spring"))) return;
	Modify();
	int32 NewOptionalPins = OptionalPins;
	if (bInUseSpring) NewOptionalPins |= static_cast<int32>(EWidgetTransitionOptionalPin::Spring);
	else NewOptionalPins &= ~static_cast<int32>(EWidgetTransitionOptionalPin::Spring);
	const bool bNewShowEasing = !bInUseSpring;
	if (OptionalPins == NewOptionalPins && bShowEasing == bNewShowEasing) return;
	OptionalPins = NewOptionalPins;
	bShowEasing = bNewShowEasing;
	ReconstructNode();
}

bool UK2Node_WidgetTransition::IsCustomEasingSelected() const
{
	return SelectedEasingPreset == TEXT("Custom");
}

void UK2Node_WidgetTransition::SetSelectedEasingPreset(FName InPreset)
{
	if (SelectedEasingPreset == InPreset) return;
	Modify();
	SelectedEasingPreset = InPreset;
	ReconstructNode();
}

FWidgetTransitionEasingValue UK2Node_WidgetTransition::GetDisplayedEasingValue() const
{
	FWidgetTransitionEasingValue Value;
	if (!IsCustomEasingSelected())
	{
		if (const FWidgetTransitionEasing* Preset = GetDefault<UWidgetTransitionSettings>()->FindEasing(SelectedEasingPreset))
		{
			Value.ControlPoint1 = Preset->ControlPoint1;
			Value.ControlPoint2 = Preset->ControlPoint2;
		}
		else { Value.ControlPoint1 = FVector2D::ZeroVector; Value.ControlPoint2 = FVector2D(1.0f, 1.0f); }
		return Value;
	}
	if (const UEdGraphPin* EasingPin = FindPin(WidgetTransitionNode::EasingPinName))
	{
		if (EasingPin->SubPins.Num() == 2)
		{
			Value.ControlPoint1.InitFromString(EasingPin->SubPins[0]->GetDefaultAsString());
			Value.ControlPoint2.InitFromString(EasingPin->SubPins[1]->GetDefaultAsString());
		}
		else FWidgetTransitionEasingValue::StaticStruct()->ImportText(*EasingPin->DefaultValue, &Value, nullptr, PPF_None, nullptr, TEXT("Easing"));
	}
	return Value;
}

void UK2Node_WidgetTransition::SetPropertyValueType(EWidgetTransitionValueType InValueType)
{
	Modify();
	ValueType = InValueType;
	bValueTypeResolved = true;
	bValuePinsDisabled = false;
	if (!SupportsTransitionMode(TEXT("Spring")))
	{
		OptionalPins &= ~static_cast<int32>(EWidgetTransitionOptionalPin::Spring);
		bShowEasing = true;
	}
	ReconstructNode();
}
